// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package main

import "fmt"

const (
	_Mode_name_0 = "ReadWrite"
	_Mode_name_1 = "Execute"
)

var (
	_Mode_index_0 = [...]uint8{0, 4, 9}
	_Mode_index_1 = [...]uint8{0, 7}
)

func (i Mode) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Mode_name_0[_Mode_index_0[i]:_Mode_index_0[i+1]]
	case i == 4:
		return _Mode_name_1
	default:
		return fmt.Sprintf("Mode(%d)", i)
	}
}
